// <auto-generated />
using System;
using HygieneAudit.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HygieneAudit.Infrastructure.Migrations
{
    [DbContext(typeof(HygieneAuditDbContext))]
    partial class HygieneAuditDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HygieneAudit.Domain.Entities.Audit", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsGas")
                        .HasColumnType("bit");

                    b.Property<int>("PicId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PicId");

                    b.HasIndex("TenantId");

                    b.ToTable("Audits");
                });

            modelBuilder.Entity("HygieneAudit.Domain.Entities.AuditItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuditId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuditId");

                    b.ToTable("AuditItems");
                });

            modelBuilder.Entity("HygieneAudit.Domain.Entities.AuditItemPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuditItemId")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuditItemId");

                    b.ToTable("AuditItemPhotos");
                });

            modelBuilder.Entity("HygieneAudit.Domain.Entities.ChecklistTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresGas")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ChecklistTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "LIFE SAFETY",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Kondisi Pipa Gas di Area Tenant",
                            RequiresGas = true
                        },
                        new
                        {
                            Id = 2,
                            Category = "LIFE SAFETY",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Interkoneksi Gas dengan Exhaust Fan",
                            RequiresGas = true
                        },
                        new
                        {
                            Id = 3,
                            Category = "LIFE SAFETY",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Sensor Kebocoran Gas",
                            RequiresGas = true
                        },
                        new
                        {
                            Id = 4,
                            Category = "LIFE SAFETY",
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Penutup Otomatis (Solenoid Valve)",
                            RequiresGas = true
                        },
                        new
                        {
                            Id = 5,
                            Category = "LIFE SAFETY",
                            DisplayOrder = 5,
                            IsActive = true,
                            Name = "Alarm Warning System",
                            RequiresGas = false
                        },
                        new
                        {
                            Id = 6,
                            Category = "LIFE SAFETY",
                            DisplayOrder = 6,
                            IsActive = true,
                            Name = "Sprinkler, Smoke/Heat Detector",
                            RequiresGas = false
                        },
                        new
                        {
                            Id = 7,
                            Category = "LIFE SAFETY",
                            DisplayOrder = 7,
                            IsActive = true,
                            Name = "Alat Pemadam Api Ringan (APAR)",
                            RequiresGas = false
                        },
                        new
                        {
                            Id = 8,
                            Category = "LIFE SAFETY",
                            DisplayOrder = 8,
                            IsActive = true,
                            Name = "Fire Suppression System",
                            RequiresGas = false
                        },
                        new
                        {
                            Id = 9,
                            Category = "LIFE SAFETY",
                            DisplayOrder = 9,
                            IsActive = true,
                            Name = "Lampu Emergency",
                            RequiresGas = false
                        },
                        new
                        {
                            Id = 10,
                            Category = "LIFE SAFETY",
                            DisplayOrder = 10,
                            IsActive = true,
                            Name = "Signage Exit",
                            RequiresGas = false
                        },
                        new
                        {
                            Id = 11,
                            Category = "LIFE SAFETY",
                            DisplayOrder = 11,
                            IsActive = true,
                            Name = "Kotak P3K/First Aid",
                            RequiresGas = false
                        },
                        new
                        {
                            Id = 12,
                            Category = "SIRKULASI UDARA",
                            DisplayOrder = 12,
                            IsActive = true,
                            Name = "Ducting & Filter Hood",
                            RequiresGas = true
                        },
                        new
                        {
                            Id = 13,
                            Category = "INSTALASI PIPA AIR BERSIH",
                            DisplayOrder = 13,
                            IsActive = true,
                            Name = "Pipa Supply",
                            RequiresGas = false
                        },
                        new
                        {
                            Id = 14,
                            Category = "SALURAN PEMBUANGAN",
                            DisplayOrder = 14,
                            IsActive = true,
                            Name = "Gutter & Floor Drain",
                            RequiresGas = false
                        },
                        new
                        {
                            Id = 15,
                            Category = "SALURAN PEMBUANGAN",
                            DisplayOrder = 15,
                            IsActive = true,
                            Name = "Grease Trap",
                            RequiresGas = true
                        },
                        new
                        {
                            Id = 16,
                            Category = "SALURAN PEMBUANGAN",
                            DisplayOrder = 16,
                            IsActive = true,
                            Name = "Pemilahan Minyak Bekas",
                            RequiresGas = true
                        },
                        new
                        {
                            Id = 17,
                            Category = "INSTALASI LISTRIK",
                            DisplayOrder = 17,
                            IsActive = true,
                            Name = "Instalasi Listrik",
                            RequiresGas = false
                        },
                        new
                        {
                            Id = 18,
                            Category = "INSTALASI LISTRIK",
                            DisplayOrder = 18,
                            IsActive = true,
                            Name = "Panel Listrik",
                            RequiresGas = false
                        },
                        new
                        {
                            Id = 19,
                            Category = "INSTALASI LISTRIK",
                            DisplayOrder = 19,
                            IsActive = true,
                            Name = "Penerangan Area Kitchen",
                            RequiresGas = true
                        },
                        new
                        {
                            Id = 20,
                            Category = "KEBERSIHAN AREA",
                            DisplayOrder = 20,
                            IsActive = true,
                            Name = "Kebersihan",
                            RequiresGas = false
                        },
                        new
                        {
                            Id = 21,
                            Category = "KEBERSIHAN AREA",
                            DisplayOrder = 21,
                            IsActive = true,
                            Name = "Kerapihan",
                            RequiresGas = false
                        },
                        new
                        {
                            Id = 22,
                            Category = "KEBERSIHAN AREA",
                            DisplayOrder = 22,
                            IsActive = true,
                            Name = "Sampah",
                            RequiresGas = false
                        },
                        new
                        {
                            Id = 23,
                            Category = "KEBERSIHAN AREA",
                            DisplayOrder = 23,
                            IsActive = true,
                            Name = "General Cleaning",
                            RequiresGas = false
                        },
                        new
                        {
                            Id = 24,
                            Category = "PEST CONTROL",
                            DisplayOrder = 24,
                            IsActive = true,
                            Name = "Vendor Pest Control",
                            RequiresGas = false
                        },
                        new
                        {
                            Id = 25,
                            Category = "PEST CONTROL",
                            DisplayOrder = 25,
                            IsActive = true,
                            Name = "Tidak Ada Celah (Dinding/Ceiling)",
                            RequiresGas = false
                        },
                        new
                        {
                            Id = 26,
                            Category = "PERSONAL HYGIENE",
                            DisplayOrder = 26,
                            IsActive = true,
                            Name = "Personal Hygiene SOP",
                            RequiresGas = false
                        },
                        new
                        {
                            Id = 27,
                            Category = "SERTIFIKASI",
                            DisplayOrder = 27,
                            IsActive = true,
                            Name = "Sertifikasi Hygiene",
                            RequiresGas = false
                        });
                });

            modelBuilder.Entity("HygieneAudit.Domain.Entities.SyncQueueItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("bit");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SyncQueue");
                });

            modelBuilder.Entity("HygieneAudit.Domain.Entities.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Floor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UsesGas")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Restoran",
                            CreatedAt = new DateTime(2026, 5, 19, 3, 38, 23, 618, DateTimeKind.Utc).AddTicks(7724),
                            Floor = "LG",
                            IsActive = true,
                            Name = "Teras by Plataran",
                            UsesGas = true
                        },
                        new
                        {
                            Id = 2,
                            Category = "Kafe",
                            CreatedAt = new DateTime(2026, 5, 19, 3, 38, 23, 618, DateTimeKind.Utc).AddTicks(7728),
                            Floor = "G",
                            IsActive = true,
                            Name = "Starbucks Coffee",
                            UsesGas = true
                        },
                        new
                        {
                            Id = 3,
                            Category = "Retail",
                            CreatedAt = new DateTime(2026, 5, 19, 3, 38, 23, 618, DateTimeKind.Utc).AddTicks(7730),
                            Floor = "2",
                            IsActive = true,
                            Name = "Gramedia Bookstore",
                            UsesGas = false
                        },
                        new
                        {
                            Id = 4,
                            Category = "Retail",
                            CreatedAt = new DateTime(2026, 5, 19, 3, 38, 23, 618, DateTimeKind.Utc).AddTicks(7732),
                            Floor = "1",
                            IsActive = true,
                            Name = "H&M Fashion",
                            UsesGas = false
                        },
                        new
                        {
                            Id = 5,
                            Category = "Restoran",
                            CreatedAt = new DateTime(2026, 5, 19, 3, 38, 23, 618, DateTimeKind.Utc).AddTicks(7733),
                            Floor = "3",
                            IsActive = true,
                            Name = "Sushi Tei",
                            UsesGas = true
                        });
                });

            modelBuilder.Entity("HygieneAudit.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 19, 3, 38, 23, 618, DateTimeKind.Utc).AddTicks(7573),
                            IsActive = true,
                            Name = "Administrator",
                            PasswordHash = "$2a$11$MlU7tuaJIbKYYSzk4nnE/ubbS8sqVdhcwPN523z4ZlSs6o6fVBLDO",
                            Role = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 19, 3, 38, 23, 618, DateTimeKind.Utc).AddTicks(7578),
                            IsActive = true,
                            Name = "Budi Santoso",
                            PasswordHash = "$2a$11$K7YLnOyngILPisuPnBSD.ObjSwl9hgAYjqH9C5Mh8ZuSsGPGU4njK",
                            Role = 0,
                            Username = "auditor1"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 19, 3, 38, 23, 618, DateTimeKind.Utc).AddTicks(7580),
                            IsActive = true,
                            Name = "Dewi Kusuma",
                            PasswordHash = "$2a$11$K7YLnOyngILPisuPnBSD.ObjSwl9hgAYjqH9C5Mh8ZuSsGPGU4njK",
                            Role = 0,
                            Username = "auditor2"
                        });
                });

            modelBuilder.Entity("HygieneAudit.Domain.Entities.Audit", b =>
                {
                    b.HasOne("HygieneAudit.Domain.Entities.User", "Pic")
                        .WithMany()
                        .HasForeignKey("PicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HygieneAudit.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Audits")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pic");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("HygieneAudit.Domain.Entities.AuditItem", b =>
                {
                    b.HasOne("HygieneAudit.Domain.Entities.Audit", "Audit")
                        .WithMany("Items")
                        .HasForeignKey("AuditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Audit");
                });

            modelBuilder.Entity("HygieneAudit.Domain.Entities.AuditItemPhoto", b =>
                {
                    b.HasOne("HygieneAudit.Domain.Entities.AuditItem", "AuditItem")
                        .WithMany("Photos")
                        .HasForeignKey("AuditItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditItem");
                });

            modelBuilder.Entity("HygieneAudit.Domain.Entities.Audit", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("HygieneAudit.Domain.Entities.AuditItem", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("HygieneAudit.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Audits");
                });
#pragma warning restore 612, 618
        }
    }
}
